export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const COLLECTIONS_LOADING = 'COLLECTIONS_LOADING';
export const COLLECTIONS_LOADED = 'COLLECTIONS_LOADED';
export const COLLECTIONS_FAILED = 'COLLECTIONS_FAILED';
export const ADD_COLLECTION = 'ADD_COLLECTION';

export const SEARCH_CREATED = 'SEARCH_CREATED';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const SEARCH_ID = 'SEARCH_ID';
export const SEARCH_SUCCESSFUL = 'SEARCH_SUCCESSFUL';
export const CLEAR_SEARCH_ERROR = 'CLEAR_SEARCH_ERROR';
export const NUMBER_OF_PAGES = 'NUMBER_OF_PAGES';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

export const METADATA_LOADING = 'METADATA_LOADING';
export const METADATA_FAILED = 'METADATA_FAILED';
export const METADATA_SUCCESSFUL = 'METADATA_SUCCESSFUL';
export const ADD_ACTIVE_METADATA = 'ADD_ACTIVE_METADATA';

export const GRAPH_DATA_FAILED = 'GRAPH_DATA_FAILED';
export const GRAPH_DATA_LOADING = 'GRAPH_DATA_LOADING';
export const GRAPH_DATA_SUCCESSFUL = 'GRAPH_DATA_SUCCESSFUL';
