export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const COLLECTIONS_LOADING = 'COLLECTIONS_LOADING';
export const COLLECTIONS_LOADED = 'COLLECTIONS_LOADED';
export const COLLECTIONS_FAILED = 'COLLECTIONS_FAILED';
export const ADD_COLLECTION = 'ADD_COLLECTION';